### ISSUE TITLE
Duplicate players can be created

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/CoverMyPingPong#1]

**Comment by jlholm** [comment]
For this I am just going to add a unique constraint on the players name. I'm not sure if I want to setup actual user accounts yet. Let me know what you think

**Comment by Serneum** [comment]
That's all I was going to do as well unless you were going to make users more complex by having them tied to some other model

**Comment by jlholm** [comment]
This was fixed: #5 

When deploying to Heroku this is going to throw an error. Will need to cleanup data before migration
