### ISSUE TITLE
Move "New Player" button to more visible location

### ISSUE THREAD

**Issue by jlholm** [ElixirCLE/CoverMyPingPong#14]
Current "New Player" button on /users page is at the bottom of the player table and is not clearly visible. Consider moving its location to the top right of the table head

**Comment by Serneum** [comment]
:+1: I was thinking about making it an actual button in the upper right

**Comment by jlholm** [comment]
I'm cool with that. Spectre has [dropdown buttons](https://picturepan2.github.io/spectre/components.html#dropdowns) that we could use in the top nav bar

**Comment by Serneum** [comment]
I meant the upper right of the players index (so right above the table). That being said, also adding a dropdown button where the button takes you to the list of players but clicking the caret and having the ability to go directly to adding a new player could be an additional set of work
