### ISSUE TITLE
Setup ExMachina & proper testing structure

### ISSUE THREAD

**Issue by jlholm** [ElixirCLE/CoverMyPingPong#6]
- [ ] Setup ExMachina
- [ ] Get initial testing structure setup
- [ ] Start writing tests

**Comment by Serneum** [comment]
Was this completed today? I thought I saw ExMachina come through in [your PR](https://github.com/ElixirCLE/CoverMyPingPong/pull/7/files#diff-a53562b003f8b881cfccc3050e85eddeR1)

**Comment by jlholm** [comment]
Ya, guess I can close this
